### ISSUE TITLE
Bug: food is too close to the wall

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#10]
Hey guys, 
Last-minute bug: sometimes is get GAME OVER from just because the piece of food is near to the wall.
It seems like if the food is near the wall then the snake automatically enters the game over area too. 
@FrancescaMichielan would you be so nice to fix it, please?

**Comment by FrancescaMichielan** [comment]
Hi Giulio,
I've corrected the issue in food.py file by restricting the area where the piece of food can be put randomly. 
Please, see changes here https://github.com/giuntac/Snake-Game/commit/8312c41c219c9dd295e52cc826ed939a1c5b1aaf.
