### ISSUE TITLE
Adding the username and score features

### ISSUE THREAD

**Issue by giuntac** [giuntac/Snake-Game#11]
Hey guys! Now that the game works, it would be awesome to be able to implement a database holding usernames and scores, where our players can save their score and lookup high scores etc.

**Comment by giuliosmall** [comment]
Hey @giuntac! 
It was quite tough but we finally made it! The database is now implemented in the backend: users can store their username and score. They can set the username they want with `main.py -u YOURUSERNAME` and if the score is bigger than zero, it will be added to the SQLite database. Solved here https://github.com/giuntac/Snake-Game/commit/48faee4172e717edfbd76f808114d5aecab7a2f0.
