### ISSUE TITLE
The new structure is good, now we need a README

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#12]
Hey @povelatorachele @FrancescaMichielan , would you be so nice to provide a detailed `README` in the main folder describing the project? 
But, please, pay attention: _with great power comes great responsibility_ 🤓

**Comment by povelatorachele** [comment]
Hey guys, I started writing the README file in the update_readme branch and I added a gift explaining how the game works. @FrancescaMichielan can you please go on adding the remaining parts to the file?

**Comment by giuntac** [comment]
Hey guys! After @FrancescaMichielan added the last parts, I corrected a couple typos and added a section for "Authors" where we can all be reached, check it out at 4facf05 🤓
I hope you all like this final version!
