### ISSUE TITLE
Score additional features

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#13]
Hey @giuntac,
We all need your SQL skills 🔧 . It would be nice if users can check the overall scoreboard (possibly ordered). It will spur the competition and engagement indeed!
Could we count on you, right?

**Comment by giuntac** [comment]
Hey Giulio! Herw we go. With this moduel users can check the leaderboard, check the highest score and look for a specific user's score. 
Closed in https://github.com/giuntac/Snake-Game/commit/cd0676139fc474272087c45b43bee21ed6e63863
