### ISSUE TITLE
Adding documentation

### ISSUE THREAD

**Issue by giuntac** [giuntac/Snake-Game#14]
Hey guys! We're almost done. However, we're missing a big part of our project for potential users: documentation. Let's work on a first draft folllwing the guidelines we were given.

**Comment by giuntac** [comment]
Hye guys, here is a first draft of the documentation.
You can see the changes at https://github.com/giuntac/Snake-Game/commit/72ddb4d6b0753489edc7939bb6c6e812e8793ddc
Check it out and let me know what you think!

**Comment by FrancescaMichielan** [comment]
Hi Cecilia, you did a great job!! 
Since we add more functions in the main.py file, we need to add also the related documentation.
Tell me if you can do it!!😁

**Comment by giuntac** [comment]
You're right! I added the needed modification for the new functions.
Check it out in https://github.com/giuntac/Snake-Game/commit/c7dd8110b27cfa17d1f6df6bb318282a13ed6612 😎
