### ISSUE TITLE
Directory reorganisation

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#18]
Ciao @giuntac,
There is a little mess within the project structure. The package is now live so we can remove the presence of double files. 
Let me know if you need any further help.
Best of luck

**Comment by giuntac** [comment]
Hey Giulio! I deleted the double files so now everything that is supposed to be in the package is just in there.
Fixed in https://github.com/giuntac/Snake-Game/commit/ed805c4548d198337028d0015b96143f090d4f55
