### ISSUE TITLE
usability features!!

### ISSUE THREAD

**Issue by FrancescaMichielan** [giuntac/Snake-Game#19]
Hey guys I was wondering about 2 more issues:
1. it might be better for the users to change the usability features from the terminal rather than modify the csv file;
2. and re organise the code to let the users if he want to play immediately or see statistics regarding the scoreboard. 

Let me know what you think!

**Comment by giuliosmall** [comment]
Ciao @FrancescaMichielan,
It should work fine now. The user can choose wether: 

- to play with `main.py -u YOURUSERNAME`
- to check statistics about the leaderboard with `main.py -c` or `main.py` -m or `main.py -l`

Solved here https://github.com/giuntac/Snake-Game/commit/139c43c4f28536951b1efcb7d75f1c85c23ac999
