### ISSUE TITLE
Create a class for grouping the first three tasks

### ISSUE THREAD

**Issue by povelatorachele** [giuntac/Snake-Game#2]
Group the code of the following tasks in order to increase the usability of the code and the clearness of the project:
- Create the snake body (snake_body branch)
- Move the snake body (Move_Snake branch)
- Control the snake with the arrow keys (controlling_snake branch)

**Comment by giuntac** [comment]
The class was created in https://github.com/giuntac/Snake-Game/commit/e3ee00edf5a899df5c983cebddc87e99d18300d3 
However, the game is not working: the snake appears and the screen stays open but it does not move and I can't control it.
Please, look into this problem with the new organization of the code.

**Comment by povelatorachele** [comment]
This issue was solved in bd924d0 
The problem with the code was easier than I thought! Anyway, I simply recalled the move function of the snake class in main so as to be able to move the snake and control it with the arrow keys.
