### ISSUE TITLE
No call to food refresh function in main.py

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#4]
Add in main.py the condition for which the food changes position randomly every time the snake hits the food.

**Comment by FrancescaMichielan** [comment]
Thanks @giuliosmall I was working on the file in the moment you mentioned me in this issue, I solved it here https://github.com/giuntac/Snake-Game/commit/2d96b5f17e75f6429b78f936e5fcb272fa89d80c. 
I saw also that in the file food.py there were some repetition and I solved them here ae910a26d56fa77aa5256c1a2231422d02238593.
