### ISSUE TITLE
Scoreboard 

### ISSUE THREAD

**Issue by FrancescaMichielan** [giuntac/Snake-Game#5]
It might be a good idea to add the score on the game by adding a scoreboard!

**Comment by FrancescaMichielan** [comment]
I worked on it a lot, and I'm sorry for all the commits I have done. 
I created the new class that keep track of the score, this is the last version 42d10e7c9ce61145cfd3b3360c14cca5b6cdaff9. 

There is a problem since, the scoreboard appear only after the Snake eat the first piece of food, this means that 'Score: 0" do not appear on video screen. @giuliosmall @giuntac @povelatorachele, maybe you are able to solve the issue.

**Comment by giuliosmall** [comment]
Thanks, @FrancescaMichielan for your stellar work.
Tested by the team and it's officially working 🤩
Solved here https://github.com/giuntac/Snake-Game/commit/3804d3e3f9ef364d5250b2bf86773b94c971df51.
