### ISSUE TITLE
The game is infinite looping 

### ISSUE THREAD

**Issue by povelatorachele** [giuntac/Snake-Game#6]
I've just checked if the code runs properly and well, it works but the game seems to loop infinitely. We need to prevent the snake from running off one side of the screen by implementing wall collision! Are you able to do it?

**Comment by giuliosmall** [comment]
Great catch @povelatorachele! Thanks for letting me noticing it 😊
Now, if the snake hits walls, the game ends up in GAME OVER mode.
Solved in https://github.com/giuntac/Snake-Game/commit/eb42ac29f2736cbeca62b47fa5214f0beb3abd99 .
