### ISSUE TITLE
Hitting the tail does not stop the game

### ISSUE THREAD

**Issue by giuliosmall** [giuntac/Snake-Game#7]
Up to this point, the game works spectacularly! Well done! 
I just realized that there is one additional missing feature, that is fundamental for the functioning of the game: **the tail collision**.  Right now, if the head hits the tail, the game keeps going. @povelatorachele please, would you be so nice to fix it?

**Comment by povelatorachele** [comment]
I solved this issue in 8a660f1 and its parent commit a53fd18 in two passages: firstly, I added a segment to the snake body every time the snake eats food and then, I detected the collision with the tail. Now, every time the head of the snake hits the tail, it's GAME OVER!!!!
