### ISSUE TITLE
Code formalities 

### ISSUE THREAD

**Issue by giuntac** [giuntac/Snake-Game#8]
I was enhancing the code by using slicing in the last part of the code to detect collision with the tail. When trying out the code, an error came up saying "inconsistent use of tabs and spaces in indentation". 
Now is probably a good time to fix our code in order to have it comply with Python conventions as we saw in class!

**Comment by giuliosmall** [comment]
Hey @giuntac, no worries. It was just a minor fix. It now works. 
Solved here https://github.com/giuntac/Snake-Game/commit/032ad9efadb92da854e81843bf8bb10a531707ba .

**Comment by giuliosmall** [comment]
Guys, this game works spectacularly 😎
Just a general comment: what about **pep-8** style? It seems like we must reformat the code following pep-8 style guidelines. What do you say? @povelatorachele @giuntac  @FrancescaMichielan

**Comment by povelatorachele** [comment]
No worries @giuliosmall, I've taken care of it in 762177e5aaeb7f60dfb4d152d35ebe2a60286179 and its parent commits in pep8 branch! Now all the Python files in our project respect PEP-8 rules! 😎
